parameters:
#    al_taxonomy.example.class: ActiveLAMP\TaxonomyBundle\Example

services:
#    al_taxonomy.example:
#        class: %al_taxonomy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
