language: php

php:
  - 5.5
  - 5.4

mysql:
  database: symfony
  username: root

env:
  - SYMFONY_VERSION=2.3.6
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update

  # Install symfony full stack and symlink the bundle.
  - composer -n create-project symfony/framework-standard-edition ../../symfony/ ${SYMFONY_VERSION}
  - cd ../../symfony/src
  - ln -s ../../activelamp/taxonomy-bundle/src/* ./
  - cd ..

  # Register the bundle and add routes.
  - php ../activelamp/taxonomy-bundle/tests/setup_app.php

  # Setup the database
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create

  # Remove the Demo tests
  - rm -rf src/Acme/DemoBundle/Tests

script: phpunit -c app --debug
